FormidableLabs/builder

- README.md
In reference to the good discussion we had on #13 , here's an update to the README to include:
* A better introduction and some motivations / use cases.
* A section on "how to remove builder" to underscore the adherence to "just npm"
* Note: Documentation relies on https://github.com/FormidableLabs/builder/pull/18 being merged (which has the new `ARCHTETYPE-dev` thing).
/cc @boygirl @colinmegill @ianobermiller
> README: Add better introduction, motivation and removal section.

- .travis.yml
- HISTORY.md
- README.md
- lib/config.js
- lib/runner.js
- lib/task.js
I've got to wire this PR up, the `builder-react-component` one, and then verify the whole soup-to-nuts thing works in `formidable-react-component-boilerplate`. I'm also adding `npm v3` matrix env vars to all Travis Builds along the way -- we should ticket out / implement the same for Victory repos as many of our developers use `npm v3` which Travis doesn't / the rest of us don't which makes for a bumpy ride for some unsuspecting folks.
* `builder-react-component` PR: https://github.com/FormidableLabs/builder-react-component/pull/6
Remove `builder install` workflow in favor of a split `ARCHETYPE` / `ARCHETYPE-dev` publishing scheme that eases NPM v3 transition.
* Fixes #17 #15
* Closes #14
* Relates to #16
NPM v3's insistence on placing dependencies flatly makes things inconsistent / …
> Feature dev deps refactor

- lib/config.js
Fixes #25
@david-davidson -- Can you try out:
```js
"builder": "FormidableLabs/builder#bug-archetype-path-npm3"
```
in your sandbox and report back here?
/cc @david-davidson @boygirl @exogen
> Add npmv3 sibling archetype package location detection.

- lib/config.js
Fixes #30 
* Infer sibiling dependencies as a fallback if installed from NPM at all (v3 or v2)
* Also throw in a `require.resolve` as another fallback method.
/cc @exogen @boygirl
> Change to more permissive sibling dependency inference.

- lib/config.js
Fixes #32
Way simpler and don't care if sibling dependencies anymore!
/cc @exogen @boygirl
> Chore: Use straight require for ARCHETYPE/package.json

- README.md
- lib/args.js
- lib/config.js
- lib/runner.js
- lib/task.js
- package.json
This PR:
Fixes #16
Fixes #37 
* Adds in basic support for arbitrary command flags for builder. Using `nopt` because that's what `npm` uses and our mantra is "just like `npm`" :wink: 
* Adds `builder run --retries=NUM TASK`
* Aliases `builder run` to `builder help` #37 
* Adds `builder help run` specific help with specific flags
* Adds `--builderrc=PATH` global command flag.
* Removes deprecated `builder install` #16
My use case for this is retries for `requirepack` functional tests (where I can't use magellan).
/cc @chaseadamsio @boygirl @exogen
> Chore: Add `--retries=NUM` to `builder run`

- .eslintrc-server-test
- .istanbul.server.yml
- .travis.yml
- README.md
- lib/args.js
- lib/config.js
- lib/runner.js
- lib/task.js
- package.json
- test/server/mocha.opts
- test/server/setup.js
- test/server/spec/base.spec.js
- test/server/spec/lib/args.spec.js
* Add --queue=NUM flag to 'concurrent'
* Add --buffer flag to 'concurrent'
* Add default options to flags in 'args'
* Add basic unit tests for 'args' parsing logic
* Add infrastructure for sinon, mocha, chai, karma
* Hook up Travis to coveralls for coverage reports
* Update README docs
* Add 'LOCAL_DEV' env variable option for 'npm link' local development
* BUGFIX: Make displayHelp() show unique tasks.
/cc @chaseadamsio @exogen @aisapatino
> Add --queue, --buffer flags, default options and args tests.

- HISTORY.md
- lib/environment.js
- lib/task.js
Fixes #47 
We now have a more sensible PATH / NODE_PATH resolution order.
Also:
* Update links on HISTORY
* Minor flags fix for `builder run`
/cc @dandelany @boygirl @exogen @chaseadamsio 
@dandelany @boygirl @exogen -- Can one of you try this out in an erroring Victory repo? Thanks!
> BUG: Fix PATH/NODE_PATH resolution order.

- README.md
- lib/args.js
- lib/runner.js
- lib/task.js
- test/server/spec/lib/args.spec.js
Fixes #29
* Implement 'builder envs'
* Add flag '--envs-path'
* Update documentation.
* Add tests for args for envs action.
/cc @chaseadamsio @exogen
> Implement 'builder envs' action.

- README.md
- bin/builder-core.js
- bin/builder.js
Alternative PR to #26 
Fixes #10 
* Separates out `builder-core`
* Adds local detection and switch.
/cc @chaseadamsio
> Add local detect and switch for builder.

- lib/task.js
Help originally worked like:
```
$ builder help <archetype1> <archetype2>
```
Then I broke things making it:
```
$ builder help <action>
```
Now, with this PR it does the "right thing" with:
```
$ builder help <action>
$ builder help <archetype1> <archetype2>
```
In the `action` case it displays tailored help for that action.
In the `archetype` case it displays only those tasks for that archetype.
/cc @coopy @exogen @boygirl
> BUG: Fix help

- README.md
- bin/builder-core.js
- lib/args.js
- lib/runner.js
- lib/utils/tracker.js
- package.json
- test/server/spec/lib/args.spec.js
**Note**: New and improved version of deprecated #54 . The issues I was having that prompted this change include:
* `--setup` invoked tasks would linger around after the normal actions terminated.
* `--setup` errors were not stoping the underlying actions from happening.
... so without further ado:
Fixes #51
* Add --setup feature for task over lifetime of actions.
* Abort actions with error if setup fails.
* Move tracker to separate file.
* Have tracker kill entire process tree of tasks.
* Wait on tracker to kill everything before finishing tasks.
* Add convenience helper functions.
/cc @exogen @chaseadamsio @boygirl @coopy
> Add --setup feature, enhance tracker ps killing.

- lib/runner.js
`builder envs` did not work on Node 4+ because `_.merge` was behaving differently due to `process.env` no longer being a plain object. This clones `shOpts` (which contains `env`) so that merge works as expected.
I considered `_.toPlainObject(process.env)` in `environment.js` in place of this fix, to fix the problem at its source. That worked, but I was fearful of the implications as Environment explicitly says that `env` is "environment object to mutate" – and using that fix we'd no longer be mutating `process.env` but a copy.
Fixes #63
/cc @ryan-roemer
> Fix merging of process.env in Node 4+

- lib/runner.js
Fixes #62
/cc @exogen @chaseadamsio @coopy
> Add higher maxBuffer to 'exec()' options on invocation. 

- .travis.yml
- README.md
- lib/args.js
- lib/runner.js
- lib/task.js
- package.json
- test/server/spec/lib/runner.spec.js
Fixes https://github.com/FormidableLabs/builder-react-component/issues/27
Also adds a little CI check to have _builder itself_ run the CI test task.
This is **take two** of this PR as the complex scenario is: should I add the ` -- ` to the _next_ underlying task. We now have a resolution of this which is:
1. If a builder task, then _yes_
2. Otherwise _no_
You can see this in action with the builder-react-component where I pass `--help` all the way down to `karma` instead of having it run the test like normal.
```sh
$ formidable-react-component-boilerplate $ builder run test -- --help
[builder:proc:start] Command: builder run npm:test -- --help
[builder:proc:start] Command: builder run test-frontend -- --help
[builder:proc:start] Command: karma start …
```
> Feature: Add '--' custom arguments support.

- README.md
Adds a _lot_ more detail on how to munge with `PATH`. We'll link this and cobble together a `tl;dr` gist to paste into the Victory repos to help deal with confusion over https://github.com/FormidableLabs/victory/issues/170
/cc @knowbody @mxstbr @coopy @boygirl
> Chore: Add enhanced local install / PATH documentation.

- README.md
- lib/args.js
- lib/task.js
- test/server/spec/lib/args.spec.js
* Make `builder` with no arguments display help. Fixes #61
* Add `-h|--help` flags for help.
* Add `-v|--version` flags for version.
/cc @coopy @baer @zachhale @chaseadamsio @benbayard @boygirl
> Add version support and -h|--help flags.

- .eslintrc-server-test
- README.md
- bin/builder-core.js
- lib/config.js
- lib/log.js
- lib/runner.js
- lib/task.js
- lib/utils/tracker.js
- package.json
- test/server/fixtures/repeat-script.js
- test/server/setup.js
- test/server/spec/base.spec.js
- test/server/spec/bin/builder-core.spec.js
- test/server/spec/lib/args.spec.js
Implementation work for #9
* Add comprehensive "almost" functional tests in `builder-core.spec.js` using `mock-fs` and a
ton of actual usage scenarios.
* Capture JSON parsing errors for `builder envs` better.
* Fix bug wherein `builder --version` displayed help instead of version.
* Refactor `--setup` execution model to resolve and use a `Task` object straight up
rather than a `builder run <setup-task-name>`.
* Refactor `config.js` and `log.js` to have stubable methods in tests.
* Enhance `builder-core` to take an options argument.
* Fix minor README.md typo.
/cc @chaseadamsio @benbayard @baer @coopy @zachhale
> Add significantly more test coverage and various bug/doc fixes.

- HISTORY.md
- README.md
- lib/config.js
- lib/environment.js
- lib/task.js
- test/server/fixtures/echo.js
- test/server/spec/bin/builder-core.spec.js
* Add `config` support for `builder` process execution environment + tests. Fixes #89.
* Add docs with explanation of `npm` and `builder` config implementations.
* Enhance existing tests.
* Fix many missing `package.json` mock files in tests.
* Add ignoring `builder:`-prefixed test.
* Add `builder envs` with `--envs-paths=FILE` test.
/cc @coopy @zachhale @boygirl @benbayard @chaseadamsio @shakefon
> Add support for `package.json:config` analogous to `npm`.

- README.md
- lib/args.js
- lib/runner.js
- lib/task.js
- package.json
- test/server/spec/lib/runner.spec.js
* Refactor to use environment instead of `--` appending to propagate to
`builder` commands. Fixes #92
* Add note for https://github.com/FormidableLabs/builder/issues/93
* Remove `argv-split` as we're not parsing commands anymore.
/cc @zachhale @coopy
> Pass `--` custom flags through environment.

- HISTORY.md
- README.md
- lib/args.js
- lib/config.js
- lib/environment.js
- lib/runner.js
- lib/task.js
- test/server/spec/bin/builder-core.spec.js
- test/server/spec/lib/args.spec.js
- test/server/spec/lib/runner.spec.js
* Revises `PATH`, `NODE_PATH` ordering to place archetype first, then root
project.
* Add `--expand-archetype` flag to expand `node_modules/<archetype` tokens in
task strings.
Fixes FormidableLabs/builder-victory-component#23
* Refactors `config.js` to streamline package.json ingestion and pass back
more data.
* Updated docs and lots of tests.
This PR subsumes https://github.com/FormidableLabs/builder/pull/90 and switches to "archetype-first" for path resolution.
For `victory` git installs to work, we need additional changes in the archetype (add this new flag to `npm:postinstall` and webpack changes). https://github.com/FormidableLabs/builder-victory-component/compare/feature-expand-archetype
/cc @boygirl @coopy @exogen @zachhale @chaseadamsio @shakefon
> Revise `PATH`, `NODE_PATH` ordering + add `--expand-archetype` flag

- .eslintrc-server-test
- HISTORY.md
- README.md
- bin/builder-core.js
- bin/builder.js
- lib/args.js
- lib/log.js
- test/server/spec/base.spec.js
- test/server/spec/bin/builder-core.spec.js
- test/server/spec/lib/args.spec.js
* Refactor `builder.js` to pass a buffer of messages to builder to be
later logged.
* Refactor to queue up log statements until `log.setLevel()` is called. The
issue we're solving is logging in "./environment" when environment is
needed to determine what level to log at.
* Adds `--log-level=info|warn|error|none` flag. Fixes #6
* Adds `--quiet` flag as alias for `--log-level=none`.
* Adds env variable `_BUILDER_ARGS_LOG_LEVEL=info|warn|error|none` to also
control.
* Add tests and docs.
These new controls should allow us to easily set things for test commands. Closes #66
**Note**: I'm not totally sure this won't break in earlier `builder` global installs. We may need to educate folks generally to update if we see any errors for `setLevel()` not being defined / a function.
/cc @chaseadamsio …
> Configurable log levels for builder itself.

- README.md
See https://github.com/FormidableLabs/builder/issues/105
@ryan-roemer This is a guesstimate based on a conversation with @divmain about why `npm link` causes problems when developing archetypes. I'd love if you could vet this and/or explain it better than I just did!
> Warn about using `npm link` when developing archetypes

- README.md
* Add documentation on how to use the module pattern for dev dependencies.
Fixes #107
* Add documentation on how to use for application dependencies. Fixes #83 
* Have example PR with refactor at: https://github.com/FormidableLabs/builder-react-component/pull/39
/cc @coopy @boygirl @chaseadamsio @shakefon @exogen @baer
> Document "the module pattern" for using prod/dep archetype dependencies.

- lib/config.js
- test/server/spec/bin/builder-core.spec.js
* Add permissive traverse of package.json's when searching for configs. Fixes #113
* Add regression test.
/cc @jchip @shakefon
> BUG: Allow root package.json to omit config.

- HISTORY.md
- README.md
- lib/args.js
- lib/runner.js
- lib/spawn.js
- package.json
- test/server/spec/base.spec.js
- test/server/spec/bin/builder-core.spec.js
- test/server/spec/lib/args.spec.js
- test/server/spec/lib/spawn.spec.js
This fixes the failing repro case from #120, but breaks the tests. If we go this route we need to rethink how we're capturing child process output in our tests, because stubbing `process.stdout.write` doesn't work anymore – a pretty major problem for our test suite.
The magic that makes it work is the `stdio: "inherit"` option to `spawn` (this is also what breaks the tests). AFAIK using anything but `"inherit"` won't work (I tried, and could still repro the issue).
This currently just makes the existing `buffer` option a no-op, but we could easily bring it back: if `buffer` is specified we'd switch off `stdio: "inherit"` and use `stdio: "pipe"` (the default) instead, buffering the output ourselves like `exec` would do.
Tasks:
Tickets:
* Need continued work to solve #120
* Fixes #20
> Spawn commands like npm

- test/server/spec/bin/builder-core.spec.js
Now that we use `spawn` and have a new method of capturing stdio in tests, let's unskip the `--setup` tests. (They haven't flaked on me yet, but we can try triggering CI multiple times if it was only happening rarely.)
Fixes #86.
/cc @ryan-roemer
> Unskip --setup tests to check flakiness

- HISTORY.md
- bin/builder.js
Use the "safe exit" pattern from https://github.com/nodejs/node-v0.x-archive/issues/3737 to exit with our return code when the process is naturally ready. This will prevent any pending piped output [edit: from *us*, in case some other process is running `builder`] from being truncated.
Fixes #124.
> Exit when the process is ready and has flushed stdout

- .travis.yml
- README.md
- appveyor.yml
- lib/environment.js
- lib/log.js
- lib/runner.js
- lib/utils/clone.js
- stdout-%npm_package_config__proc_num%.log
- test/func/package.json
- test/func/test.sh
- test/server/spec/base.spec.js
- test/server/spec/bin/builder-core.spec.js
- test/server/spec/lib/runner.spec.js
* Fixes #123 
* Copies `process.env` and mutates a copy everywhere.
* Fixes previously undiscovered bugs with expand archetypes on Windows
/cc @exogen
> Chore: Add appveyor CI

- HISTORY.md
- lib/args.js
- lib/log.js
- lib/task.js
- test/server/spec/bin/builder-core.spec.js
- test/server/spec/lib/args.spec.js
* Default log level to `none` for `help` and `version` commands. Fixes #127
* Minor HISTORY.md cleanup
/cc @exogen
> Default log level to `none` for `help` and `version` commands. 

- .travis.yml
- HISTORY.md
- README.md
- appveyor.yml
- bin/builder-core.js
- lib/args.js
- lib/environment.js
- lib/task.js
- lib/utils/json.js
- test/server/fixtures/echo.js
- test/server/spec/bin/builder-core.spec.js
- test/server/spec/lib/args.spec.js
* Adds `--env`, `--env-path` flags so you can add cross-OS-compatible environment variables via a JSON object.
* Updates travis ci matrix
* Abstract json parsing to utility.
* Fix indentation level of some sections. Fixes #131 
/cc @exogen
> Feature: `--env`, `--env-path` flags.

- .travis.yml
- appveyor.yml
This adds the new npm v4 to our Travis and AppVeyor builds.
* In the Travis config, the `NPM_3` var was changed to `TEST_NPM_VERSION`.
* In the AppVeyor config, instead of always installing `npm@next`, we install 3 and 4 for each supported version of Node. I'm guessing since we were installing `npm@next` before, then npm 2.x was never part of this build. We could add it, but this PR currently just continues existing tradition.
* npm is now installed globally in the AppVeyor config. This is a more realistic setup, and it's working fine for me in my `postinstall-build` CI.
/cc @ryan-roemer
> Add npm v4 to CI build matrix

- HISTORY.md
- bin/builder-core.js
- lib/config.js
- lib/environment.js
- lib/runner.js
- lib/utils/archetype.js
* Add in `NODE_PATH` and `PATH` from _actual resolved paths_ of prod and dev archetypes instead of guessed paths. This will better support `yarn`, which flattens `node_modules/.bin` in different ways than real `npm`. It is also likely more correct than before. Fixes #134
* Add extra higher level directory check when `LOCAL_DEV=true` and `--expand-archetype` specified.
* Make config loading failure a simple `log.info` instead of `log.warn`.
/cc @exogen @kenwheeler @paulathevalley
> Bug: Use actual archetype resolved paths to enhance NODE_PATH and PATH

- HISTORY.md
- README.md
- lib/args.js
- lib/config.js
- lib/log.js
- lib/task.js
- lib/utils/runner.js
- lib/utils/setup.js
- test/func/spec/func.spec.js
- test/server/spec/bin/builder-core.spec.js
- Add `debug` log level. Fixes #160 
- Refactor existing messages to have some be `default` instead of `info`
- **Breaking**: Default to `--log-level=none` in CLI
> [MAJOR] Chore: Debug log level, default to quiet

- .travis.yml
- HISTORY.md
- appveyor.yml
- package.json
- Restrict engines to node4. Part of #158
- Update CI
- Update docs
> [MAJOR] Restrict to node4
